[package]
name = "glam-pbr"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
glam = { version = ">=0.19, <=0.22", features = ["libm"], default-features = false }
num-traits = { version = "0.2.15", default-features = false }
